### ISSUE TITLE
Gracefully fail when running it in the context of a pull-request

### ISSUE THREAD

**Issue by drupol** [DeterminateSystems/update-flake-lock#16]
Hello,

I'm using your Github action in my own workflow.

I noticed that when it is run through a pull-request, it doesn't work: https://github.com/loophp/flake-lock-update-workflow/pull/5

The issue is: 

```
  Error: When the repository is checked out on a commit instead of a branch, the 'base' input must be supplied.
```

**Comment by cole-h** [comment]
I'm a bit unclear on what exactly you expect to happen -- are you expecting a PR to be created against this new pull request, or are you expecting the action to push directly to the PR's branch?

**Comment by drupol** [comment]
I think creating a PR against this PR is the best way to handle this.

**Comment by grahamc** [comment]
That seems a bit strange to me, I think it is much more common for these types of PRs to come outside of other PRs. Do you know of other actions that behave this way?

**Comment by drupol** [comment]
What do you find strange? Creating a PR against another PR ?

Creating PR against another PR is doable, as you can see here: https://github.com/loophp/flake-lock-update-workflow/pull/5 (the latest commits).

**Comment by drupol** [comment]
Hi there,

> Can you explain your use case more fully, and why you want PRs to also have flake.lock updates?

It's not that I need it myself, but someone might.

Let's say we maintain multiple branches of a project, we need to update the `flake.lock` file in those branches.
As a PR is actually a temporary branch, I'm wondering if we shouldn't support that feature.

If the person creating a PR branched out on an outdated parent branch, then it might make sense.

WDYT?

Note: I discover this behavior by chance. Maybe we should update the action and fail gracefully when it's within a PR ? I don't know.

**Comment by grahamc** [comment]
I think we should probably not, today, support running in the context of a PR, and instead setup the cron to operate on all the long running branches.

I think it would be a good idea to detect and fail gracefully if it is in a PR.

**Comment by drupol** [comment]
I agree.

**Comment by cole-h** [comment]
Sorry it took so long to get back to this.

There's no easy way to tell GitHub (in the action itself) to "skip" it under certain conditions. I came up with one potential solution in https://github.com/DeterminateSystems/update-flake-lock/pull/30, but the drawback is that the action still succeeds instead of getting marked as skipped.

However, I've opened a PR at https://github.com/DeterminateSystems/update-flake-lock/pull/31 that documents how you can get GitHub to skip the action if it could ever be triggered by a PR: guard the step using our action with `if: ${{ github.event_name != 'pull_request' }}`.

**Comment by drupol** [comment]
Very nice ! Thanks !
