### ISSUE TITLE
Allow automerge

### ISSUE THREAD

**Issue by pingiun** [DeterminateSystems/update-flake-lock#27]
Either integrate the https://github.com/peter-evans/enable-pull-request-automerge project, or output the PR number such that this the enable-pull-request-automerge action can be tacked on after update-flake-lock

**Comment by cole-h** [comment]
I think I'd prefer just exposing the PR number. Since we use https://github.com/peter-evans/create-pull-request/ under the good, and that action exposes the PR number, it shouldn't be too difficult to re-expose that for you to use with the automerge action :)

I think I'll be able to take a look at this soon.

**Comment by cole-h** [comment]
I've opened https://github.com/DeterminateSystems/update-flake-lock/pull/28 that exposes a `pull-request-number` output, as well as documented how to use it in the README. Please take a look and let me know if that satisfies your needs!
