### ISSUE TITLE
Since v11, this action now creates a second commit

### ISSUE THREAD

**Issue by dhess** [DeterminateSystems/update-flake-lock#40]
Thanks for this action.

Unfortunately, since v11, the action now creates 2 commits: the flake update, and a second commit that commits `pr_body.template` and `pr_body.txt`. For example, see this PR:

https://github.com/hackworthltd/hacknix/pull/560

(Unfortunately, I didn't notice this until after Mergify committed the PR.)

(I created that PR by running the action using a manual workflow, so perhaps that's related.)

Here's the resuable workflow we're using, for reference:

https://github.com/hackworthltd/.github/blob/main/.github/workflows/reusable-update-nix-flake-public.yml

Prior to upgrading to v11, it worked great.

**Comment by cole-h** [comment]
Thanks for the report, I'll take a look. Sorry for the unintentional mess!

**Comment by cole-h** [comment]
I've just published a v12 that fixes this issue (reproduced in https://github.com/cole-h/update-flake-lock-test/pull/26, fix demonstrated in https://github.com/cole-h/update-flake-lock-test/pull/25).

Sorry again for the issue, and thanks for opening a ticket about it!

**Comment by cole-h** [comment]
For a brief bit of background, the action we use to actually create the PR, https://github.com/peter-evans/create-pull-request, commits all new and modified files when it runs, and https://github.com/DeterminateSystems/update-flake-lock/pull/38 introduced functionality to customize the PR body by using a template file.

The fix was to remove the undesired files before that action runs, as suggested in https://github.com/peter-evans/create-pull-request#remove-files.
